a = int(input("Enter the first number: "))
b = int(input("enter the sencond number: "))
print("\nSimple Calculator")
print("===================")
print("A =",a)
print("B =",b)
print(" ")
print(a,"plus", b, "=" ,a+b)
print(a,"minus", b, "=" ,a-b)
print(a,"times", b, "=" ,a*b)
print(a,"divided by", b, "=" ,a/b)
print(a,"Remainder after division", b, "=" ,a%b)